DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS urls;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
  );

  CREATE TABLE urls (
    id SERIAL PRIMARY KEY,
    shortURL VARCHAR(255) UNIQUE NOT NULL,
    longURL TEXT NOT NULL
  );